services:
  db:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  mailpit:
    image: axllent/mailpit:v1.27
    ports:
      - "1025:1025"
      - "8025:8025"
