name: Suggestion
description: Suggest an idea for this project
labels: ['suggestion']
body:
  - type: markdown
    id: problems
    attributes:
      label: Related problems
      description: Is your request related to a problem? Please describe.
  - type: markdown
    id: description
    attributes:
      label: Description
      description: Describe the solution you'd like
    validations:
      required: true
  - type: markdown
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the suggestion here.
