name: 🚀📄 Suggestion (User Story)
description: Suggest an idea for this project as a user story
title: 'As a ____, I want ____, so that I can ____'
labels: ['suggestion']
body:
  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: Describe your suggestion more in detail - what do you want to happen?
    validations:
      required: true
  - type: textarea
    id: criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: What needs to be done for this user story to be considered finished?
      placeholder: |
        - [ ] Does the horse donkey?
        - [ ] Flux capacitor charged
        - [ ] Can reach 88 MPH
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: 💡 Additional context
      description: Add any other context or screenshots about the suggestion here.
