// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"time"
)

type News struct {
	ID        int32
	Title     string
	Content   string
	CreatedAt time.Time
}
