name: Code validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  WORKFLOW_NODE_VERSION: 24.x

jobs:
  test:
    name: Unit tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1

      - name: Use Node.js ${{ env.WORKFLOW_NODE_VERSION }}
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.WORKFLOW_NODE_VERSION }}

      - name: pnpm install
        run: npm install -g pnpm@12.3.4

      - run: pnpm install --frozen-lockfile

      - run: pnpm test

  run-linters:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1

      - name: Use Node.js ${{ env.WORKFLOW_NODE_VERSION }}
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.WORKFLOW_NODE_VERSION }}

      - name: pnpm install
        run: npm install -g pnpm@12.3.4

      - run: pnpm install --frozen-lockfile
        id: install_dependencies 

      - name: ESLint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-annotations
          filter_mode: ${{ (github.event_name == 'pull_request') && 'file' || 'nofilter' }}
          fail_level: warning
          level: ${{ (github.event_name == 'pull_request') && 'error' || 'warning' }}
          tool_name: ESLint

      - name: Prettier
        if: ${{ !cancelled() && steps.install_dependencies.outcome == 'success' }}
        uses: EPMatt/reviewdog-action-prettier@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-annotations
          filter_mode: ${{ (github.event_name == 'pull_request') && 'file' || 'nofilter' }}
          fail_level: warning
          level: ${{ (github.event_name == 'pull_request') && 'error' || 'warning' }}
          tool_name: Prettier
