name: Code validation

on:
  push:
    branches: [main]
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
    branches: [main]

env:
  WORKFLOW_NODE_VERSION: 20.x

jobs:
  test:
    name: Unit tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.WORKFLOW_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.WORKFLOW_NODE_VERSION }}

      - name: pnpm install
        run: npm install -g pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm test

  run-linters:
    name: Execute linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.WORKFLOW_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.WORKFLOW_NODE_VERSION }}

      - name: pnpm install
        run: npm install -g pnpm

      - run: pnpm install prettier

      - run: pnpm install --frozen-lockfile

      - name: ESLint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-annotations
          filter_mode: ${{ (github.event_name == 'pull_request') && 'file' || 'nofilter' }}
          level: ${{ (github.event_name == 'pull_request') && 'error' || 'warning' }}
          fail_on_error: true
          tool_name: ESLint

      - name: Prettier
        uses: recitalsoftware/reviewdog-action-prettier@515af15b62f88daec74c7d93d1c29b62dd0b8e11
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-annotations
          filter_mode: ${{ (github.event_name == 'pull_request') && 'file' || 'nofilter' }}
          level: ${{ (github.event_name == 'pull_request') && 'error' || 'warning' }}
          fail_on_error: true
          tool_name: Prettier
